export const LANGUAGE_CODES = [
  "SC",
  "TC-TW",
  "TC-HK",
  "JP",
  "KR",
  "HERITAGE",
] as const;
export const CATEGORIES = [
  "sans",
  "serif",
  "rounded",
  "mono",
  "handwriting",
  "pixel",
] as const;
export const LICENSE_FILTERS = ["OFL", "Apache", "MIT", "Other"] as const;

export type LanguageCode = (typeof LANGUAGE_CODES)[number];
export type Category = (typeof CATEGORIES)[number];
export type LicenseFilter = (typeof LICENSE_FILTERS)[number];
export type CoverageLevel = "full" | "partial" | "experimental" | "none";
export type FontStatus = "active" | "archived" | "beta";

export const GLYPH_LABELS: Record<LanguageCode, string> = {
  SC: "簡體",
  "TC-TW": "繁體（臺灣）",
  "TC-HK": "繁體（香港）",
  JP: "日文",
  KR: "韓文",
  HERITAGE: "傳承字形",
};

export interface FontLanguage {
  languageCode: LanguageCode;
  coverageLevel: CoverageLevel;
  note?: string;
}

export interface FontRecord {
  id: number;
  slug: string;
  name: string;
  displayName?: string;
  description?: string;
  license: string;
  baseFont?: string;
  status?: FontStatus;
  sourceUrl?: string;
  repoUrl?: string;
  homepageUrl?: string;
  author?: string;
  category: Category;
  isVariable: boolean;
  isSourceHanDerivative: boolean;
  cssFontFamily?: string;
  previewCssUrl?: string;
  notes?: string;
  languages: FontLanguage[];
  tags: string[];
}

const panCjkLanguages: FontLanguage[] = [
  { languageCode: "SC", coverageLevel: "full" },
  { languageCode: "TC-TW", coverageLevel: "full" },
  { languageCode: "TC-HK", coverageLevel: "full" },
  { languageCode: "JP", coverageLevel: "full" },
  { languageCode: "KR", coverageLevel: "full" },
];

export const catalogFonts: FontRecord[] = [
  {
    id: 1,
    slug: "noto-sans-cjk",
    name: "Noto Sans CJK",
    displayName: "Noto Sans CJK",
    description:
      "A comprehensive pan-CJK sans serif family developed by Google for Chinese, Japanese, and Korean text.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/noto/specimen/Noto+Sans+SC",
    repoUrl: "https://github.com/notofonts/noto-cjk",
    homepageUrl: "https://fonts.google.com/noto",
    author: "Google",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Noto Sans SC', 'Noto Sans CJK SC', sans-serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;700&display=swap",
    notes:
      "Google Fonts preview uses the Simplified Chinese subset. Other regional glyph sets are available through Noto CJK releases.",
    languages: panCjkLanguages,
    tags: ["pan-cjk", "gothic", "ui"],
  },
  {
    id: 2,
    slug: "noto-serif-cjk",
    name: "Noto Serif CJK",
    displayName: "Noto Serif CJK",
    description:
      "A pan-CJK serif family designed for high-quality long-form Chinese, Japanese, and Korean typography.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/noto/specimen/Noto+Serif+SC",
    repoUrl: "https://github.com/notofonts/noto-cjk",
    homepageUrl: "https://fonts.google.com/noto",
    author: "Google",
    category: "serif",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Noto Serif SC', 'Noto Serif CJK SC', serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@400;700&display=swap",
    notes:
      "Google Fonts preview uses the Simplified Chinese subset. Use regional Noto CJK packages for production pan-CJK typesetting.",
    languages: panCjkLanguages,
    tags: ["pan-cjk", "songti", "mincho"],
  },
  {
    id: 3,
    slug: "source-han-sans",
    name: "Source Han Sans",
    displayName: "思源黑體 / 源ノ角ゴシック",
    description:
      "Adobe and Google's open-source pan-CJK sans serif family, distributed as Source Han Sans and Noto Sans CJK.",
    license: "OFL-1.1",
    sourceUrl: "https://github.com/adobe-fonts/source-han-sans",
    repoUrl: "https://github.com/adobe-fonts/source-han-sans",
    homepageUrl: "https://github.com/adobe-fonts/source-han-sans",
    author: "Adobe + Google",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Source Han Sans', 'Noto Sans CJK SC', sans-serif",
    notes:
      "Same glyph project as Noto Sans CJK with different packaging and naming. No web preview CSS is bundled by this catalog.",
    languages: panCjkLanguages,
    tags: ["pan-cjk", "gothic", "adobe"],
  },
  {
    id: 4,
    slug: "source-han-serif",
    name: "Source Han Serif",
    displayName: "思源宋體 / 源ノ明朝",
    description:
      "Adobe and Google's open-source pan-CJK serif family for editorial and long-form CJK typography.",
    license: "OFL-1.1",
    sourceUrl: "https://source.typekit.com/source-han-serif/",
    repoUrl: "https://github.com/adobe-fonts/source-han-serif",
    homepageUrl: "https://github.com/adobe-fonts/source-han-serif",
    author: "Adobe + Google",
    category: "serif",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Source Han Serif', 'Noto Serif CJK SC', serif",
    notes:
      "Same glyph project as Noto Serif CJK with different packaging and naming. No web preview CSS is bundled by this catalog.",
    languages: panCjkLanguages,
    tags: ["pan-cjk", "mincho", "adobe"],
  },
  {
    id: 5,
    slug: "sarasa-gothic",
    name: "Sarasa Gothic",
    displayName: "更紗黑體",
    description:
      "A CJK programming typeface based on Iosevka and Source Han Sans, useful for code and multilingual UI.",
    license: "OFL-1.1",
    sourceUrl: "https://github.com/be5invis/Sarasa-Gothic",
    repoUrl: "https://github.com/be5invis/Sarasa-Gothic",
    author: "be5invis",
    category: "mono",
    isVariable: false,
    isSourceHanDerivative: true,
    cssFontFamily: "'Sarasa Gothic', 'Sarasa Mono SC', monospace",
    notes:
      "The project ships many regional and width variants. Choose the package that matches your script and code style needs.",
    languages: panCjkLanguages,
    tags: ["mono", "programming", "gothic"],
  },
  {
    id: 6,
    slug: "lxgw-wenkai",
    name: "LXGW WenKai",
    displayName: "霞鶩文楷",
    description:
      "A readable open-source Kaiti-style typeface with a warm handwritten texture for Chinese text.",
    license: "OFL-1.1",
    baseFont: "Klee One",
    status: "active",
    sourceUrl: "https://github.com/lxgw/LxgwWenKai",
    repoUrl: "https://github.com/lxgw/LxgwWenKai",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW WenKai TC', 'LXGW WenKai', cursive",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=LXGW+WenKai+TC:wght@400;700&display=swap",
    notes:
      "Traditional Chinese preview is available through Google Fonts. Simplified Chinese support is partial in this MVP catalog entry.",
    languages: [
      { languageCode: "TC-TW", coverageLevel: "full" },
      { languageCode: "SC", coverageLevel: "partial" },
    ],
    tags: ["kaiti", "handwriting", "reading"],
  },
  {
    id: 7,
    slug: "m-plus-1p",
    name: "M PLUS 1p",
    displayName: "M PLUS 1p",
    description:
      "A geometric Japanese sans serif with a wide weight range and approachable screen texture.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/specimen/M+PLUS+1p",
    repoUrl: "https://github.com/coz-m/MPLUS_FONTS",
    author: "Coji Morishita",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'M PLUS 1p', sans-serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@400;700&display=swap",
    languages: [{ languageCode: "JP", coverageLevel: "full" }],
    tags: ["japanese", "geometric", "ui"],
  },
  {
    id: 8,
    slug: "zen-kaku-gothic",
    name: "Zen Kaku Gothic",
    displayName: "Zen Kaku Gothic New",
    description:
      "A contemporary Japanese gothic family with clean strokes for headings, UI, and body text.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/specimen/Zen+Kaku+Gothic+New",
    repoUrl: "https://github.com/googlefonts/zen-kakugothic",
    author: "Google",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Zen Kaku Gothic New', sans-serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New:wght@400;700&display=swap",
    languages: [{ languageCode: "JP", coverageLevel: "full" }],
    tags: ["japanese", "gothic", "ui"],
  },
  {
    id: 9,
    slug: "zen-maru-gothic",
    name: "Zen Maru Gothic",
    displayName: "Zen Maru Gothic",
    description:
      "A rounded Japanese gothic family with soft terminals and friendly display character.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/specimen/Zen+Maru+Gothic",
    repoUrl: "https://github.com/googlefonts/zen-marugothic",
    author: "Google",
    category: "rounded",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Zen Maru Gothic', sans-serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@400;700&display=swap",
    languages: [{ languageCode: "JP", coverageLevel: "full" }],
    tags: ["japanese", "rounded", "friendly"],
  },
  {
    id: 10,
    slug: "shippori-mincho",
    name: "Shippori Mincho",
    displayName: "Shippori Mincho",
    description:
      "A refined Japanese mincho typeface inspired by traditional book typography.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/specimen/Shippori+Mincho",
    repoUrl: "https://github.com/fontdasu/ShipporiMincho",
    author: "Google",
    category: "serif",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Shippori Mincho', serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=Shippori+Mincho:wght@400;700&display=swap",
    languages: [{ languageCode: "JP", coverageLevel: "full" }],
    tags: ["japanese", "mincho", "books"],
  },
  {
    id: 11,
    slug: "pretendard",
    name: "Pretendard",
    displayName: "Pretendard",
    description:
      "A Korean UI sans serif derived from Inter and Source Han Sans with broad modern interface use.",
    license: "OFL-1.1",
    sourceUrl: "https://cactus.tistory.com/306",
    repoUrl: "https://github.com/orioncactus/pretendard",
    homepageUrl: "https://github.com/orioncactus/pretendard",
    author: "orioncactus",
    category: "sans",
    isVariable: true,
    isSourceHanDerivative: true,
    cssFontFamily: "'Pretendard', sans-serif",
    notes:
      "No external preview CSS is loaded by this MVP. Install or self-host Pretendard for production usage.",
    languages: [{ languageCode: "KR", coverageLevel: "full" }],
    tags: ["korean", "ui", "variable"],
  },
  {
    id: 12,
    slug: "d2coding",
    name: "D2Coding",
    displayName: "D2Coding",
    description:
      "Naver's Korean monospaced coding font, designed for Hangul readability in development tools.",
    license: "OFL-1.1",
    sourceUrl: "https://github.com/naver/d2codingfont",
    repoUrl: "https://github.com/naver/d2codingfont",
    author: "Naver",
    category: "mono",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'D2 Coding', monospace",
    notes:
      "Google Fonts availability can vary; this MVP leaves remote preview CSS disabled unless a verified CSS endpoint is added.",
    languages: [{ languageCode: "KR", coverageLevel: "full" }],
    tags: ["korean", "mono", "programming"],
  },
  {
    id: 13,
    slug: "maple-mono-nf-cn",
    name: "Maple Mono NF CN",
    displayName: "Maple Mono NF CN",
    description:
      "A clean monospaced font with programming ligatures, supporting Chinese characters.",
    license: "OFL-1.1",
    repoUrl: "https://github.com/subframe7536/maple-font",
    author: "subframe7536",
    category: "mono",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Maple Mono NF CN', monospace",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "partial" },
    ],
    tags: ["mono", "programming", "chinese"],
  },
  {
    id: 14,
    slug: "zen-old-mincho",
    name: "Zen Old Mincho",
    displayName: "Zen Old Mincho",
    description:
      "A traditional Japanese mincho typeface with classical proportions.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/specimen/Zen+Old+Mincho",
    author: "Google",
    category: "serif",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Zen Old Mincho', serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=Zen+Old+Mincho:wght@400;700&display=swap",
    languages: [{ languageCode: "JP", coverageLevel: "full" }],
    tags: ["japanese", "mincho", "classical"],
  },
  {
    id: 15,
    slug: "kosugi",
    name: "Kosugi",
    displayName: "Kosugi",
    description:
      "A clean Japanese gothic typeface designed for screen readability.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/specimen/Kosugi",
    author: "Google",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Kosugi', sans-serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=Kosugi:wght@400;700&display=swap",
    languages: [{ languageCode: "JP", coverageLevel: "full" }],
    tags: ["japanese", "gothic", "screen"],
  },
  {
    id: 16,
    slug: "kosugi-maru",
    name: "Kosugi Maru",
    displayName: "Kosugi Maru",
    description:
      "A rounded Japanese gothic typeface with soft, friendly character.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/specimen/Kosugi+Maru",
    author: "Google",
    category: "rounded",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Kosugi Maru', sans-serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=Kosugi+Maru:wght@400;700&display=swap",
    languages: [{ languageCode: "JP", coverageLevel: "full" }],
    tags: ["japanese", "rounded", "friendly"],
  },
  {
    id: 17,
    slug: "sawarabi-gothic",
    name: "Sawarabi Gothic",
    displayName: "Sawarabi Gothic",
    description:
      "A Japanese gothic typeface with balanced proportions for body text.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/specimen/Sawarabi+Gothic",
    author: "Google",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Sawarabi Gothic', sans-serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=Sawarabi+Gothic:wght@400;700&display=swap",
    languages: [{ languageCode: "JP", coverageLevel: "full" }],
    tags: ["japanese", "gothic", "body"],
  },
  {
    id: 18,
    slug: "sawarabi-mincho",
    name: "Sawarabi Mincho",
    displayName: "Sawarabi Mincho",
    description:
      "A Japanese mincho typeface inspired by traditional printing.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/specimen/Sawarabi+Mincho",
    author: "Google",
    category: "serif",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Sawarabi Mincho', serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=Sawarabi+Mincho:wght@400;700&display=swap",
    languages: [{ languageCode: "JP", coverageLevel: "full" }],
    tags: ["japanese", "mincho", "printing"],
  },
  {
    id: 19,
    slug: "suit",
    name: "SUIT",
    displayName: "SUIT",
    description:
      "A modern Korean sans-serif typeface with clean geometric forms.",
    license: "OFL-1.1",
    repoUrl: "https://github.com/sunn-us/SUIT",
    author: "Spoqa",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'SUIT', sans-serif",
    languages: [{ languageCode: "KR", coverageLevel: "full" }],
    tags: ["korean", "modern", "geometric"],
  },
  {
    id: 20,
    slug: "line-seed",
    name: "LINE Seed",
    displayName: "LINE Seed",
    description: "LINE's corporate typeface, designed for digital interfaces.",
    license: "OFL-1.1",
    repoUrl: "https://github.com/line/fonts",
    author: "LINE Corporation",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LINE Seed', sans-serif",
    languages: [
      { languageCode: "JP", coverageLevel: "full" },
      { languageCode: "KR", coverageLevel: "full" },
    ],
    tags: ["japanese", "korean", "corporate", "ui"],
  },
  {
    id: 21,
    slug: "ibm-plex-sans-kr",
    name: "IBM Plex Sans KR",
    displayName: "IBM Plex Sans KR",
    description: "IBM's corporate typeface adapted for Korean text.",
    license: "OFL-1.1",
    sourceUrl: "https://fonts.google.com/specimen/IBM+Plex+Sans+KR",
    author: "IBM",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'IBM Plex Sans KR', sans-serif",
    previewCssUrl:
      "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR:wght@400;700&display=swap",
    languages: [{ languageCode: "KR", coverageLevel: "full" }],
    tags: ["korean", "corporate", "ui"],
  },
  {
    id: 22,
    slug: "unifont",
    name: "Unifont",
    displayName: "Unifont",
    description:
      "A bitmap font covering all Unicode planes, including CJK characters.",
    license: "GPL-2.0",
    sourceUrl: "https://unifoundry.com/unifont.html",
    author: "GNU Project",
    category: "pixel",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Unifont', monospace",
    notes:
      "Bitmap font, not suitable for print. Best for terminal and pixel art.",
    languages: [
      { languageCode: "SC", coverageLevel: "partial" },
      { languageCode: "TC-TW", coverageLevel: "partial" },
      { languageCode: "JP", coverageLevel: "partial" },
      { languageCode: "KR", coverageLevel: "partial" },
    ],
    tags: ["pixel", "unicode", "bitmap"],
  },
  {
    id: 23,
    slug: "unifont-jp",
    name: "Unifont JP",
    displayName: "Unifont JP",
    description:
      "Japanese variant of Unifont with proper glyph forms for Japanese characters.",
    license: "GPL-2.0",
    sourceUrl: "https://unifoundry.com/unifont.html",
    author: "GNU Project",
    category: "pixel",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Unifont JP', monospace",
    notes: "Japanese variant with proper glyph forms.",
    languages: [{ languageCode: "JP", coverageLevel: "partial" }],
    tags: ["pixel", "unicode", "bitmap", "japanese"],
  },
  {
    id: 24,
    slug: "wenquanyi-micro-hei",
    name: "WenQuanYi Micro Hei",
    displayName: "文泉驛微米黑",
    description:
      "A Chinese sans-serif typeface designed for screen readability.",
    license: "GPL-2.0",
    sourceUrl: "https://wenq.org/en/",
    author: "WenQuanYi",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'WenQuanYi Micro Hei', sans-serif",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "partial" },
    ],
    tags: ["chinese", "screen", "sans"],
  },
  {
    id: 25,
    slug: "source-han-rounded",
    name: "Source Han Rounded",
    displayName: "思源柔黑體 / 源柔ゴシック",
    description:
      "A rounded variant of Source Han Sans, with softer terminals.",
    license: "OFL-1.1",
    repoUrl: "https://github.com/ButTaiwan/SourceHanRounded",
    author: "But Ko",
    category: "rounded",
    isVariable: false,
    isSourceHanDerivative: true,
    cssFontFamily: "'Source Han Rounded', 'Noto Sans CJK SC', sans-serif",
    languages: panCjkLanguages,
    tags: ["rounded", "source-han", "pan-cjk"],
  },
  {
    id: 26,
    slug: "chill-bitmap",
    name: "Chill Bitmap",
    displayName: "寒蟬全宋體",
    description: "A pixel/bitmap Chinese font with retro aesthetic.",
    license: "OFL-1.1",
    author: "寒蟬",
    category: "pixel",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Chill Bitmap', monospace",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "partial" },
    ],
    tags: ["pixel", "chinese", "retro"],
  },
  {
    id: 27,
    slug: "siv-gothic",
    name: "SIV Gothic",
    displayName: "獅尾黑體",
    description: "A Chinese gothic typeface with clean, modern forms.",
    license: "OFL-1.1",
    repoUrl: "https://github.com/max32002/siv-font",
    author: "Max",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'SIV Gothic', sans-serif",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "full" },
    ],
    tags: ["chinese", "gothic", "modern"],
  },
  {
    id: 28,
    slug: "xiaolai",
    name: "Xiaolai",
    displayName: "小賴字體",
    description: "基於瀨戶字體改造的開源中文手寫字體。",
    license: "OFL-1.1",
    baseFont: "瀬戸フォント",
    status: "active",
    repoUrl: "https://github.com/lxgw/kose-font",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Xiaolai SC', 'Xiaolai', cursive",
    notes: "基於瀨戶字體改造。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["chinese", "handwriting", "lxgw"],
  },
  {
    id: 29,
    slug: "yozai",
    name: "Yozai",
    displayName: "悠哉字體",
    description: "基於 Y.Oz Font 改造的開源中文手寫字體。",
    license: "OFL-1.1",
    baseFont: "Y.Oz Font",
    status: "active",
    repoUrl: "https://github.com/lxgw/yozai-font",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Yozai', cursive",
    notes: "基於 Y.Oz Font 改造。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["chinese", "handwriting", "lxgw"],
  },
  {
    id: 30,
    slug: "lxgw-marker-gothic",
    name: "LXGW Marker Gothic",
    displayName: "霞鶩漫黑",
    description: "POP 風格的開源中文黑體。",
    license: "OFL-1.1",
    baseFont: "たぬゴ角",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwMarkerGothic",
    author: "LXGW",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW Marker Gothic', sans-serif",
    notes: "POP 風格黑體。",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "partial" },
    ],
    tags: ["chinese", "gothic", "lxgw", "pop"],
  },
  {
    id: 31,
    slug: "lxgw-clear-gothic",
    name: "LXGW Clear Gothic",
    displayName: "霞鶩晰黑",
    description: "基於 IPA ex Gothic 的舊字形中文黑體。",
    license: "IPA-1.0",
    baseFont: "IPA exゴシック",
    status: "archived",
    repoUrl: "https://github.com/lxgw/LxgwClearGothic",
    author: "LXGW",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW Clear Gothic', sans-serif",
    notes: "舊字形黑體，已停止更新並歸檔。",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "partial" },
    ],
    tags: ["chinese", "gothic", "lxgw", "archived"],
  },
  {
    id: 32,
    slug: "lxgw-neo-xihei",
    name: "LXGW Neo XiHei",
    displayName: "霞鶩新晰黑",
    description: "基於 IPA ex Gothic 的大陸新字形中文黑體。",
    license: "IPA-1.0",
    baseFont: "IPA exゴシック",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwNeoXiHei",
    author: "LXGW",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW Neo XiHei', sans-serif",
    notes: "大陸新字形黑體。",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "partial" },
    ],
    tags: ["chinese", "gothic", "lxgw"],
  },
  {
    id: 33,
    slug: "lxgw-fasmart-gothic",
    name: "LXGW Fasmart Gothic",
    displayName: "霞鶩尚智黑",
    description: "基於 03 Smart Font UI 的中文黑體。",
    license: "IPA-1.0",
    baseFont: "03スマートフォントUI",
    status: "active",
    author: "LXGW",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW Fasmart Gothic', sans-serif",
    notes: "僅貓啃網發布，無獨立 GitHub 倉庫。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["chinese", "gothic", "lxgw"],
  },
  {
    id: 35,
    slug: "lxgw-zhenkai",
    name: "LXGW ZhenKai",
    displayName: "霞鶩臻楷",
    description: "基於 Klee One 的粗楷體。",
    license: "OFL-1.1",
    baseFont: "Klee One",
    status: "archived",
    repoUrl: "https://github.com/lxgw/LxgwZhenKai",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW ZhenKai', cursive",
    notes: "粗楷體，已停止更新並歸檔。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["chinese", "kaiti", "lxgw", "archived"],
  },
  {
    id: 36,
    slug: "lxgw-wenkai-tc",
    name: "LXGW WenKai TC",
    displayName: "霞鶩文楷 TC",
    description: "霞鶩文楷的臺灣繁體傳承字形版本。",
    license: "OFL-1.1",
    baseFont: "Klee One",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwWenKai",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW WenKai TC', cursive",
    notes: "傳承字形版本。",
    languages: [{ languageCode: "TC-TW", coverageLevel: "full" }],
    tags: ["traditional-chinese", "kaiti", "lxgw"],
  },
  {
    id: 37,
    slug: "lxgw-wenkai-gb",
    name: "LXGW WenKai GB",
    displayName: "霞鶩文楷 GB",
    description: "霞鶩文楷的大陸新字形版本。",
    license: "OFL-1.1",
    baseFont: "Klee One",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwWenKai",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW WenKai GB', cursive",
    notes: "大陸新字形版本。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "kaiti", "lxgw"],
  },
  {
    id: 38,
    slug: "lxgw-neo-zhisong",
    name: "LXGW Neo ZhiSong",
    displayName: "霞鶩新致宋",
    description: "基於 IPA MJ Mincho 的大陸新字形中文宋體。",
    license: "IPA-1.0",
    baseFont: "IPA mj明朝",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwNeoZhiSong",
    author: "LXGW",
    category: "serif",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW Neo ZhiSong', serif",
    notes: "大陸新字形宋體。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["chinese", "songti", "lxgw"],
  },
  {
    id: 39,
    slug: "lxgw-heart-serif",
    name: "LXGW Heart Serif",
    displayName: "霞鶩銘心宋",
    description: "基於 Kokoro Mincho 的中文宋體。",
    license: "IPA-1.0",
    baseFont: "こころ明朝体",
    status: "active",
    author: "LXGW",
    category: "serif",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW Heart Serif', serif",
    notes: "僅貓啃網發布，無獨立 GitHub 倉庫。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["chinese", "songti", "lxgw"],
  },
  {
    id: 40,
    slug: "fusion-kai",
    name: "Fusion Kai",
    displayName: "縫合楷",
    description: "由多套字體縫合而成的開源楷體。",
    license: "OFL-1.1",
    baseFont: "霞鶩文楷 GB + 芫荽 + Klee One",
    status: "active",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Fusion Kai', cursive",
    notes: "多字體縫合而成。",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "full" },
    ],
    tags: ["chinese", "kaiti", "fusion", "lxgw"],
  },
  {
    id: 41,
    slug: "lxgw-bright",
    name: "LXGW Bright",
    displayName: "LXGW Bright",
    description: "結合 Ysabeau Office 與霞鶩文楷系列的開源縫合字體。",
    license: "OFL-1.1",
    baseFont: "Ysabeau Office + 霞鶩文楷系列",
    status: "active",
    author: "LXGW",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW Bright', sans-serif",
    notes: "多字體縫合而成。",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "full" },
    ],
    tags: ["chinese", "sans", "fusion", "lxgw"],
  },
  {
    id: 42,
    slug: "lxgw-wenkai-kr",
    name: "LXGW WenKai KR",
    displayName: "霞鶩文楷韓文版",
    description: "霞鶩文楷的韓文擴充版本，補足韓文字形支援。",
    license: "OFL-1.1",
    baseFont: "Klee One",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwWenkaiKR",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW WenKai KR', cursive",
    notes: "文楷的韓文擴展版。",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "KR", coverageLevel: "full" },
    ],
    tags: ["chinese", "korean", "kaiti", "lxgw"],
  },
  {
    id: 43,
    slug: "lxgw-wenkai-lite",
    name: "LXGW WenKai Lite",
    displayName: "霞鶩文楷輕便版",
    description: "霞鶩文楷的輕量版本，適合只需要簡體中文的使用情境。",
    license: "OFL-1.1",
    baseFont: "Klee One",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwWenKai-Lite",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW WenKai Lite', cursive",
    notes: "輕量版，不含諺文和 zi2zi 生成字形。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "kaiti", "lite", "lxgw"],
  },
  {
    id: 44,
    slug: "lxgw-wenkai-gb-lite",
    name: "LXGW WenKai GB Lite",
    displayName: "霞鶩文楷GB輕便版",
    description: "霞鶩文楷 GB 新字形的輕量版本。",
    license: "OFL-1.1",
    baseFont: "Klee One",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwWenkaiGB-Lite",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW WenKai GB Lite', cursive",
    notes: "GB 新字形輕便版。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "kaiti", "lite", "lxgw"],
  },
  {
    id: 45,
    slug: "lxgw-wenkai-screen",
    name: "LXGW WenKai Screen",
    displayName: "霞鶩文楷螢幕版",
    description: "針對螢幕閱讀最佳化的霞鶩文楷版本。",
    license: "OFL-1.1",
    baseFont: "Klee One",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwWenKai-Screen",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW WenKai Screen', cursive",
    notes: "針對螢幕顯示最佳化。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "kaiti", "screen", "lxgw"],
  },
  {
    id: 46,
    slug: "lxgw-zhisong",
    name: "LXGW ZhiSong",
    displayName: "霞鶩之宋",
    description: "基於 IPA MJ 明朝的中文宋體，提供簡體完整支援。",
    license: "OFL-1.1",
    baseFont: "IPA mj明朝",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwZhiSong",
    author: "LXGW",
    category: "serif",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW ZhiSong', serif",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "partial" },
    ],
    tags: ["chinese", "songti", "lxgw"],
  },
  {
    id: 47,
    slug: "lxgw-neoxihei-code",
    name: "LXGW NeoXiHei-Code",
    displayName: "霞鶩新晰黑等寬版",
    description: "基於 IPA ex Gothic 的霞鶩新晰黑等寬版本。",
    license: "IPA-1.0",
    baseFont: "IPA exゴシック",
    status: "active",
    repoUrl: "https://github.com/lxgw/NeoXiHei-Code",
    author: "LXGW",
    category: "mono",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW NeoXiHei Code', 'LXGW NeoXiHei-Code', monospace",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "mono", "programming", "lxgw"],
  },
  {
    id: 48,
    slug: "lxgw-b5xizhi",
    name: "LXGW B5XiZhi",
    displayName: "霞鶩B5晰致",
    description: "基於 IPA ex Gothic 的繁簡中文黑體，支援 Big5 常用字形需求。",
    license: "IPA-1.0",
    baseFont: "IPA exゴシック",
    status: "active",
    repoUrl: "https://github.com/lxgw/B5XiZhi",
    author: "LXGW",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW B5XiZhi', sans-serif",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "full" },
    ],
    tags: ["chinese", "traditional-chinese", "gothic", "lxgw"],
  },
  {
    id: 49,
    slug: "lxgw-neoxizhi-screen",
    name: "LXGW NeoXiZhi-Screen",
    displayName: "霞鶩新晰致螢幕版",
    description: "霞鶩新晰致的螢幕顯示最佳化版本。",
    license: "IPA-1.0",
    baseFont: "IPA exゴシック",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwNeoXiZhi-Screen",
    author: "LXGW",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW NeoXiZhi Screen', 'LXGW NeoXiZhi-Screen', sans-serif",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "gothic", "screen", "lxgw"],
  },
  {
    id: 50,
    slug: "lxgw-neoxihei-tc",
    name: "LXGW NeoXiHeiTC",
    displayName: "霞鶩新晰黑TC",
    description: "霞鶩新晰黑的臺灣繁體版本。",
    license: "IPA-1.0",
    baseFont: "IPA exゴシック",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwNeoXiHeiTC",
    author: "LXGW",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW NeoXiHei TC', 'LXGW NeoXiHeiTC', sans-serif",
    languages: [{ languageCode: "TC-TW", coverageLevel: "full" }],
    tags: ["traditional-chinese", "gothic", "lxgw"],
  },
  {
    id: 51,
    slug: "lxgw-bright-code",
    name: "LXGW Bright-Code",
    displayName: "霞鶩Bright等寬版",
    description: "結合 Ysabeau Office 與霞鶩文楷的等寬程式字體。",
    license: "OFL-1.1",
    baseFont: "Ysabeau Office + 霞鶩文楷",
    status: "active",
    repoUrl: "https://github.com/lxgw/LxgwBright-Code",
    author: "LXGW",
    category: "mono",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW Bright Code', 'LXGW Bright-Code', monospace",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "full" },
    ],
    tags: ["chinese", "mono", "programming", "lxgw"],
  },
  {
    id: 52,
    slug: "lxgw-pengli",
    name: "LXGW Pengli",
    displayName: "霞鶩膨隸",
    description: "具隸書風格的霞鶩系列開源中文字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    repoUrl: "https://github.com/lxgw/Pengli",
    author: "LXGW",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW Pengli', cursive",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "lishu", "handwriting", "lxgw"],
  },
  {
    id: 53,
    slug: "lxgw-975gothic",
    name: "LXGW 975 Gothic",
    displayName: "霞鶩975黑體",
    description: "基於思源黑體輕度改造的霞鶩系列黑體。",
    license: "OFL-1.1",
    baseFont: "Source Han Sans (思源黑體)",
    status: "active",
    repoUrl: "https://github.com/lxgw/975gothic",
    author: "LXGW",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: true,
    cssFontFamily: "'LXGW 975 Gothic', 'Source Han Sans', sans-serif",
    notes: "思源黑體輕度改造。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "gothic", "source-han", "lxgw"],
  },
  {
    id: 54,
    slug: "lxgw-975maru",
    name: "LXGW 975 Maru",
    displayName: "霞鶩975圓體",
    description: "基於思源黑體輕度改造的霞鶩系列圓體。",
    license: "OFL-1.1",
    baseFont: "Source Han Sans (思源黑體)",
    status: "active",
    repoUrl: "https://github.com/lxgw/975maru",
    author: "LXGW",
    category: "rounded",
    isVariable: false,
    isSourceHanDerivative: true,
    cssFontFamily: "'LXGW 975 Maru', 'Source Han Sans', sans-serif",
    notes: "思源黑體輕度改造。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "rounded", "source-han", "lxgw"],
  },
  {
    id: 55,
    slug: "lxgw-i-ming",
    name: "LXGW I.Ming",
    displayName: "LXGW I.明體",
    description: "基於 I.Ming 的傳承字形明體，支援繁簡中文。",
    license: "OFL-1.1",
    baseFont: "I.Ming",
    status: "active",
    repoUrl: "https://github.com/lxgw/I.Ming",
    author: "LXGW",
    category: "serif",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'LXGW I.Ming', 'I.Ming', serif",
    notes: "傳承字形明體。",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "full" },
    ],
    tags: ["chinese", "mingti", "heritage", "lxgw"],
  },
  {
    id: 56,
    slug: "mixed-vswekai",
    name: "Mixed VsWeKai",
    displayName: "混合芫荽文楷",
    description: "混合霞鶩文楷與芫荽的開源中文楷體。",
    license: "OFL-1.1",
    baseFont: "霞鶩文楷 + 芫荽",
    status: "active",
    repoUrl: "https://github.com/FWHP-Enfun/Mixed-VsWeKai",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Mixed VsWeKai', cursive",
    notes: "文楷與芫荽混合。",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "full" },
    ],
    tags: ["chinese", "kaiti", "fusion"],
  },
  {
    id: 57,
    slug: "yshipen-shuti",
    name: "YshiPen Shuti",
    displayName: "一支筆手寫體",
    description: "臺灣繁體中文手寫風格開源字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    repoUrl: "https://github.com/Steve-Yuu/YshiPen-Shuti",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'YshiPen Shuti', cursive",
    languages: [{ languageCode: "TC-TW", coverageLevel: "full" }],
    tags: ["traditional-chinese", "handwriting", "taiwan"],
  },
  {
    id: 58,
    slug: "jyunsaikaai",
    name: "JyunSaiKaai",
    displayName: "潤疎楷",
    description: "面向繁體中文的楷書風格開源字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    repoUrl: "https://github.com/ItMarki/jyunsaikaai",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'JyunSaiKaai', cursive",
    notes: "繁體楷書。",
    languages: [{ languageCode: "TC-TW", coverageLevel: "full" }],
    tags: ["traditional-chinese", "kaiti", "handwriting"],
  },
  {
    id: 59,
    slug: "plankai",
    name: "PlanKai",
    displayName: "計畫楷",
    description: "繁體中文楷書風格的開源字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    repoUrl: "https://github.com/Des-Magmeta/PlanKai",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'PlanKai', cursive",
    languages: [{ languageCode: "TC-TW", coverageLevel: "full" }],
    tags: ["traditional-chinese", "kaiti", "handwriting"],
  },
  {
    id: 60,
    slug: "iansui",
    name: "Iansui",
    displayName: "胭脂 hatırla",
    description: "帶有臺灣手寫風格的繁體中文開源字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    repoUrl: "https://github.com/ButTaiwan/iansui",
    author: "But Ko",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Iansui', cursive",
    notes: "臺灣手寫風格。",
    languages: [{ languageCode: "TC-TW", coverageLevel: "full" }],
    tags: ["traditional-chinese", "handwriting", "taiwan"],
  },
  {
    id: 61,
    slug: "astalia",
    name: "Astalia",
    displayName: "Astalia",
    description: "支援日文排版的開源襯線字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    repoUrl: "https://github.com/Ayaginu-Sue/Astalia",
    category: "serif",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Astalia', serif",
    languages: [{ languageCode: "JP", coverageLevel: "full" }],
    tags: ["japanese", "serif"],
  },
  {
    id: 62,
    slug: "moon-stars-kai",
    name: "Moon Stars Kai",
    displayName: "星月楷",
    description: "支援繁簡中文的楷書風格開源字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    repoUrl: "https://github.com/GuiWonder/MoonStarsKai",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Moon Stars Kai', cursive",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "full" },
    ],
    tags: ["chinese", "kaiti", "handwriting"],
  },
  {
    id: 63,
    slug: "naikai-font",
    name: "Naikai Font",
    displayName: "耐楷",
    description: "面向臺灣繁體中文的開源楷書字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    repoUrl: "https://github.com/max32002/naikaifont",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Naikai Font', 'Naikai', cursive",
    languages: [{ languageCode: "TC-TW", coverageLevel: "full" }],
    tags: ["traditional-chinese", "kaiti", "handwriting"],
  },
  {
    id: 64,
    slug: "tangyuan-font",
    name: "TangYuan Font",
    displayName: "湯圓體",
    description: "圓潤可愛風格的簡體中文開源字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    repoUrl: "https://github.com/NightFurySL2001/TangYuan-font",
    category: "rounded",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'TangYuan Font', 'TangYuan', sans-serif",
    notes: "圓潤可愛風格。",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "rounded", "cute"],
  },
  {
    id: 65,
    slug: "open-huninn-font",
    name: "Open Huninn Font",
    displayName: "字咍囡⊋體",
    description: "justfont 推出的臺灣繁體中文開源黑體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    repoUrl: "https://github.com/justfont/open-huninn-font",
    author: "justfont",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'Open Huninn', 'Open Huninn Font', sans-serif",
    notes: "justfont 開源字體。",
    languages: [{ languageCode: "TC-TW", coverageLevel: "full" }],
    tags: ["traditional-chinese", "sans", "justfont"],
  },
  {
    id: 66,
    slug: "chen-yu-luo-yan",
    name: "ChenYuLuoYan Thin",
    displayName: "沉魚落雁細體",
    description: "細緻筆畫風格的中文開源黑體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    repoUrl: "https://github.com/Chenyu-otf/chenyuluoyan_thin",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'ChenYuLuoYan Thin', sans-serif",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "sans", "thin"],
  },
  {
    id: 67,
    slug: "cjkfonts-allseto",
    name: "cjkfonts AllSeto",
    displayName: "cjkfonts 全瀨戶",
    description: "cjkfonts 製作的瀨戶字體擴充版本，支援多區 CJK 文字。",
    license: "OFL-1.1",
    baseFont: "瀬戸フォント",
    status: "active",
    sourceUrl: "https://cjkfonts.io/blog/cjkfonts_allseto",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'cjkfonts AllSeto', cursive",
    notes: "瀨戶字體擴展。",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "full" },
      { languageCode: "JP", coverageLevel: "full" },
    ],
    tags: ["chinese", "japanese", "handwriting", "cjkfonts"],
  },
  {
    id: 68,
    slug: "cjkfonts-handwriting4",
    name: "cjkfonts Handwriting4",
    displayName: "cjkfonts 手寫四號",
    description: "cjkfonts 發布的簡體中文手寫風格字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    sourceUrl: "https://cjkfonts.io/blog/cjkfonts_handwriting4",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'cjkfonts Handwriting4', cursive",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "handwriting", "cjkfonts"],
  },
  {
    id: 69,
    slug: "the-peak-font",
    name: "ThePeakFont",
    displayName: "巔峰字體",
    description: "cjkfonts 發布的繁簡中文黑體字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    sourceUrl: "https://cjkfonts.io/blog/ThePeakFont",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'ThePeakFont', sans-serif",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "full" },
    ],
    tags: ["chinese", "sans", "cjkfonts"],
  },
  {
    id: 70,
    slug: "the-peak-font-plus",
    name: "ThePeakFontPlus",
    displayName: "巔峰字體Plus",
    description: "ThePeakFont 的增強版本，支援繁簡中文。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    sourceUrl: "https://cjkfonts.io/blog/ThePeakFontPlus",
    category: "sans",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'ThePeakFontPlus', sans-serif",
    notes: "ThePeakFont 增強版。",
    languages: [
      { languageCode: "SC", coverageLevel: "full" },
      { languageCode: "TC-TW", coverageLevel: "full" },
    ],
    tags: ["chinese", "sans", "cjkfonts"],
  },
  {
    id: 71,
    slug: "fancy-free-font1",
    name: "FancyFreeFont1",
    displayName: "隨心字體一號",
    description: "cjkfonts 發布的簡體中文手寫風格字體。",
    license: "OFL-1.1",
    baseFont: "待查",
    status: "active",
    sourceUrl: "https://cjkfonts.io/blog/FancyFreeFont1",
    category: "handwriting",
    isVariable: false,
    isSourceHanDerivative: false,
    cssFontFamily: "'FancyFreeFont1', cursive",
    languages: [{ languageCode: "SC", coverageLevel: "full" }],
    tags: ["simplified-chinese", "handwriting", "cjkfonts"],
  },
];

export const defaultPreviewText =
  "漢字かな交じり文 · 简体繁體中文 · 한글 테스트";
